services:
  - type: web
    name: suivi-colis-v3
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: ACCESS_CODE
        value: h2otech
